language: python

python:
  - 3.6.7

env:
  - FLASK_ENV='testing'
  
install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - pip install nose

services:
  - postgresql

before_script:
  - psql -c 'create database db_sendify;' -U postgres
  - psql -c 'create database testdb_sendify;' -U postgres 

script:
  - nosetests --with-coverage --cover-inclusive --cover-package=app

after_success:
  - coveralls